name: Code checks

on:
  workflow_dispatch:

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"